name: Dynamic Template

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV


      # Runs a set of commands using the runners shell
      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: $REPO_NAME

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $REPO_NAME
          echo ${{ github.event.repository.name }}
          echo Add other actions to build,
          echo test, and deploy your project.
