name: Dynamic Template

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls
          sed -i 's/<reponame>/$REPO_NAME/' README.md
          cat README.md
          echo $REPO_NAME

